#pragma once
#include<wx/wx.h>

DECLARE_EVENT_TYPE(wxEVT_MAP_UPDATE_REQUEST, -1)
DECLARE_EVENT_TYPE(wxEVT_MAP_UNCHECK_REQUEST, -1)

DECLARE_EVENT_TYPE(wxEVT_MAP_RECON_REQUEST, -1)
DECLARE_EVENT_TYPE(wxEVT_THREAD_END, -1)

namespace evt_id {
	const int THREAD_END_ID = 5555;
	const int MAP_UPDATE_REQUEST_ID = 5556;
	const int MAP_RECON_REQUEST_ID = 5557;
	const int MAP_UNCHECK_REQUEST_ID = 5558;
}